import type { NextPage } from 'next'
import Head from 'next/head'
import { CountdownPage } from '../src/components/CountdownPage';
import { Race } from '../src/types';
import styles from '../styles/Home.module.css'

const Home: NextPage<{ nextRace: Race }> = ({ nextRace }) => (
  <div className={styles.container}>
    <Head>
      <title>F1 Next Race Countdown</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <CountdownPage nextRace={nextRace} />
  </div>
)

export async function getStaticProps() {

  const res = await fetch('https://ergast.com/api/f1/current.json')
  const races = (await res.json())?.MRData?.RaceTable?.Races as Race[]

  const currentDate = Number(new Date())
  const nextRace = races.find((race) => Number(new Date(`${race.date} ${race.time}`)) > currentDate - 7200000)

  return {
    props: {
      nextRace,
    },
  }
}

export default Home
